#
# Standard Makefile for a Webots Fast2D plugin
#
# Author: Olivier.Michel@cyberbotics.com
# Date:   October 12th, 2003.
#

include ../Makefile.include

CFLAGS=-O3 -I/usr/local/include
LIBRARIES=-L/usr/local/lib -lan -lenkicore -lenkiinteractions
